### ISSUE TITLE
Imprimir Vuelos no tomados en Cuenta

### ISSUE THREAD

**Issue by Camirgz** [Camirgz/VueloMasBarato#5]
Usar el metodo get name para poder obtener el nombre de la aerolinea y hacer un metodo que sirva para decir que vuelo no se esta tomando en cuenta, almacenar en un string estilo

String ignorados = ""
ignorados += "Aerolinea: " + vuelo.getName + ", " + vuelo + "\n"

Al final de la interaccion se debe imprimir ignorados como 
sout(" Los siguientes vuelos no cumplian con el formato por lo que no pueden ser tomados en cuenta")

**Comment by cerillo2808** [comment]
Ya está en la clase interacción. Los vuelos ignorados van a ser imprimidos después de que se carguen todos los archivos. Luego, el programa prosigue preguntando los datos necesarios para búsquedas.
